# yaml-language-server: $schema=https://gh-dash.dev/schema.json
prSections:
  - title: Mine
    filters: is:open author:@me updated:>={{ nowModify "-3w" }}
    layout:
      author:
        hidden: true
showAuthorIcons: true
smartFilteringAtLaunch: true
