Output enhance.gif

Set PlaybackSpeed 1.3
Set Theme TokyoNight
Set Padding 0
Set FontSize 20
Set FontFamily "CommitMono Nerd Font"
Set Width 1900
Set Height 800

Hide
Type "task -- https://github.com/neovim/neovim/pull/34671"

Enter
Sleep 3s
Show

Set TypingSpeed 450ms
Sleep 1s

Type "lll"
Type@100ms "kkkkkkk"

Sleep 1s

Type@50ms "hhh"

Type "jjjj"

Type "lll"
Ctrl+D
Sleep 300ms
Ctrl+D
Sleep 300ms
Ctrl+D
Sleep 300ms
Type "/"
Type@25ms "upload"
Enter
Sleep 50ms
Type "nnnn"

Sleep 1500ms
