# https://taskfile.dev

version: "3"
silent: true

tasks:
  default:
    cmds:
      - DEBUG=true go run ./cmd/enhance {{.CLI_ARGS}}
    interactive: true
  debug:
    cmds:
      - printf "~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n―――――――――――――――――――――――――――――――――――――――――――――――\n" > ./debug.log
      - DEBUG=true go run ./cmd/enhance {{.CLI_ARGS}}
    interactive: true
  mock:
    cmds:
      - task: start-mock-server
      - defer: { task: stop-mock-server }
      - printf "~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n―――――――――――――――――――――――――――――――――――――――――――――――\n" > ./debug.log
      - cmd: DEBUG=true FF_MOCK_DATA=true go run ./cmd/enhance -R neovim/neovim 34454
  start-mock-server:
    cmds:
      - killgrave --config ./imposters/config.yml &> ./.killgrave.log  &
  local-gh:
    cmds:
      - printf "~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n―――――――――――――――――――――――――――――――――――――――――――――――\n" > ./debug.log
      - GH_PATH=/usr/local/bin/gh DEBUG=true go run ./cmd/enhance {{.CLI_ARGS}}
    interactive: true
  logs:
    cmds:
      - rm -f ./debug.log
      - touch ./debug.log
      - tail -f ./debug.log
    interactive: true
  stop-mock-server:
    cmds:
      - pkill killgrave
