# https://taskfile.dev

version: "3"
silent: true

tasks:
  default:
    cmds:
      - go run ./cmd/prc
    interactive: true
  debug:
    cmds:
      - DEBUG=true FF_MOCK_DATA=true go run ./cmd/prc
    interactive: true
  mock:
    cmds:
      - task: start-mock-server
      - task: debug
      - task: stop-mock-server
  start-mock-server:
    cmds:
      - killgrave --config ./imposters/config.yml &> ./.killgrave.log  &
    silent: true
  stop-mock-server:
    cmds:
      - pkill killgrave
    silent: true
